### PR TITLE
Fix for Scrollbar Click Closing Dropdown

### PR DESCRIPTION
**Pull request by sloped**
Fix for issue #65

### CODE REVIEW

**Comment by devBwebi** [comment]
Hey, Thanks!
But it doesn't work.
Just tried now, replaced my file with yours and the entire fancySelect disappeared.

**Comment by sloped** [comment]
Oh, woah, I must have done something wrong when compiling from coffeescript.

**Comment by devBwebi** [comment]
Sure!
glad I came across this issue.

Be waiting for a decent solution, I'm totally frustrated -_-

**Comment by sloped** [comment]
I'll try again, I am unfamiliar with coffee script and trying to replicate my fix in the JS file isn't as easy as I hoped it would be.

**Comment by devBwebi** [comment]
It you succeed it'll be awesome!
I wish I could help though ;)

**Pull request closed without merging**
